name: Bookshow 說書會
author: Bookshow
category_dir: /
permalink: pretty
exclude: [README.md]
encoding: UTF-8

root_url: bookshow.tw
google_map_url:      https://maps.google.com.tw/maps?f=q&amp;source=embed&amp;hl=zh-TW&amp;geocode=&amp;q=%E5%8F%B0%E5%8C%97%E5%B8%82%E4%BF%A1%E7%BE%A9%E5%8D%80%E5%9F%BA%E9%9A%86%E8%B7%AF%E4%B8%80%E6%AE%B5141%E8%99%9F6%E6%A8%93%E4%B9%8B7&amp;aq=&amp;sll=25.043129,121.565845&amp;sspn=0.010867,0.01914&amp;brcurrent=3,0x3442abf2b1d366ed:0x5d62b36fc2a1bb86,0,0x3442ac6b61dbbd9d:0xc0c243da98cba64b&amp;ie=UTF8&amp;hq=&amp;hnear=110%E5%8F%B0%E5%8C%97%E5%B8%82%E4%BF%A1%E7%BE%A9%E5%8D%80%E5%9F%BA%E9%9A%86%E8%B7%AF%E4%B8%80%E6%AE%B5141%E8%99%9F&amp;t=m&amp;z=14&amp;ll=25.043126,121.565843
google_map_embedded: https://maps.google.com.tw/maps?f=q&amp;source=s_q&amp;hl=zh-TW&amp;geocode=&amp;q=%E5%8F%B0%E5%8C%97%E5%B8%82%E4%BF%A1%E7%BE%A9%E5%8D%80%E5%9F%BA%E9%9A%86%E8%B7%AF%E4%B8%80%E6%AE%B5141%E8%99%9F6%E6%A8%93%E4%B9%8B7&amp;aq=&amp;sll=25.043129,121.565845&amp;sspn=0.011373,0.019848&amp;brcurrent=3,0x3442abf2b1d366ed:0x5d62b36fc2a1bb86,0,0x3442ac6b61dbbd9d:0xc0c243da98cba64b&amp;ie=UTF8&amp;hq=&amp;hnear=110%E5%8F%B0%E5%8C%97%E5%B8%82%E4%BF%A1%E7%BE%A9%E5%8D%80%E5%9F%BA%E9%9A%86%E8%B7%AF%E4%B8%80%E6%AE%B5141%E8%99%9F&amp;t=m&amp;ll=25.049602,121.564837&amp;spn=0.027215,0.051498&amp;z=14&amp;iwloc=A&amp;output=embed
google_calendar_url: https://www.google.com/calendar/embed?showTitle=0&amp;showCalendars=0&amp;showTz=0&amp;height=400&amp;wkst=2&amp;bgcolor=%23ffffff&amp;src=coe5fa4p225l8p087r6eof4ta8%40group.calendar.google.com&amp;color=%23865A5A&amp;ctz=Asia%2FTaipei
google_form_url:     https://docs.google.com/forms/d/1pBnEsLkPB_ANrAWtLTBvude4QA03PmUI1CHnfNFaaG0/viewform?embedded=true

fb: {
	image: /img/photo/space_00_l.jpg,
	desc: 分享有溫度的知識\n向世界溝通創新理念\n把活動帶到每個人眼前
}

#dev: true
